apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: etcdclusters.etcd.database.coreos.com
spec:
  group: etcd.database.coreos.com
  version: v1beta3
  scope: Namespaced
  names:
    plural: etcdclusters
    singular: etcdcluster
    kind: EtcdCluster
    listKind: EtcdClusterList
    shortNames:
      - etcdclus
      - etcd
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            version:
              type: string
            size:
              type: integer
            TLS:
              type: object
              properties:
                static:
                  type: object
                  properties:
                    member:
                      type: object
                      properties:
                        peerSecret:
                          type: string
                        serverSecret:
                          type: string
                    operatorSecret:
                      type: string
